kind: ConfigMap
apiVersion: v1
metadata:
  name: keepup-config
  namespace: keepup
data:
  APP_ENV: {{ .Values.appEnv | quote }}
  REDIS_ADDR: {{ .Values.redisAddr | quote }}
  REDIS_PORT: {{ .Values.redisPort | quote }}
  REDIS_DBNO: {{ .Values.redisDbNo | quote }}
  TTL_SECONDS: {{ .Values.ttlSeconds | quote }}
