{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keepup-ingress
  {{- if .Values.ingress.annotations }}
  annotations: {{ toYaml .Values.ingress.annotations | nindent 4 }}
  {{- end }}
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.secretName }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /os-release
            pathType: ImplementationSpecific
            backend:
              service:
                name: keepup-service
                port:
                  number: 80
          - path: /helm-cluster
            pathType: ImplementationSpecific
            backend:
              service:
                name: keepup-service
                port:
                  number: 80
          - path: /package-version
            pathType: ImplementationSpecific
            backend:
              service:
                name: keepup-service
                port:
                  number: 80
{{ end }}
