replicas: 1

main:
  image: "ghcr.io/code-tool/keepup"
  tag: ""
  pullPolicy: "IfNotPresent"

redis:
  enabled: true
  image: "redis:8.2.5"
  pullPolicy: "IfNotPresent"

ingress:
  enabled: true
  pathType: ImplementationSpecific
  ingressClassName: ""
  tls: false
  secretName: ""
  host: ""
  annotations: {}
  #  kubernetes.io/ingress.class: nginx
  #  nginx.ingress.kubernetes.io/service-upstream: "true"
  #  nginx.ingress.kubernetes.io/proxy-request-buffering: "off"

servicemonitor:
  enabled: true

annotations: {}
#  "prometheus.io/scrape": 'true'
#  "prometheus.io/port": '80'
#  "prometheus.io/path": '/metrics'

apiToken: ''
appEnv: prod
redisAddr: 127.0.0.1
redisPort: '6379'
redisDbNo: '7'
ttlSeconds: '21600'
