replicas: 1

main:
  image: "docker.io/sskorobohatko/keepup"
  tag: ""
  pullPolicy: "IfNotPresent"

redis:
  enabled: true
  image: "redis:6.2.7"
  pullPolicy: "IfNotPresent"

ingress:
  enabled: true
  pathType: ImplementationSpecific
  ingressClassName: ""
  tls: false
  secretName: ""
  host: ""

servicemonitor:
  enabled: true

annotations: {}
#  "prometheus.io/scrape": 'true'
#  "prometheus.io/port": '80'
#  "prometheus.io/path": '/metrics'

apiToken: ''
