{{- define "project.config" }}
- name: APP_ENV
  valueFrom:
    configMapKeyRef:
      name: keepup-config
      key: APP_ENV

- name: REDIS_ADDR
  valueFrom:
    configMapKeyRef:
      name: keepup-config
      key: REDIS_ADDR

- name: REDIS_PORT
  valueFrom:
    configMapKeyRef:
      name: keepup-config
      key: REDIS_PORT

- name: REDIS_DBNO
  valueFrom:
    configMapKeyRef:
      name: keepup-config
      key: REDIS_DBNO

- name: TTL_SECONDS
  valueFrom:
    configMapKeyRef:
      name: keepup-config
      key: TTL_SECONDS

- name: API_TOKEN
  valueFrom:
    secretKeyRef:
      name: keepup-seecret
      key: API_TOKEN

{{ end -}}
