apiVersion: {{$.Values.core_workloads_api}}
kind: Deployment
metadata:
  name: keepup-deployment
  labels:
    app: keepup
    type: backend
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: keepup
      type: backend
  replicas: {{ default 1 .Values.replicas }}
  template:
    metadata:
      labels:
        app: keepup
        type: backend
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
        "prometheus.io/scrape": 'true'
        "prometheus.io/port": '80'
        "prometheus.io/path": '/metrics'
    spec:
      containers:
{{ if .Values.redis.enabled  }}
      - name: keepup-redis-container
        imagePullPolicy: {{ .Values.redis.pullPolicy }}
        image: {{ .Values.redis.image | quote }}
{{ end }}    
      - name: keepup-main-container
        imagePullPolicy: {{ .Values.main.pullPolicy }}
        image: {{ .Values.main.image | quote }}
        env:
          {{ include "project.config" . | indent 10 }}
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 60  
