kind: Service
apiVersion: v1
metadata:
  name: keepup-service
  labels:
    scrapePrometheus80: 'true'
spec:
  selector:
    app: keepup
    type: backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
