name: Release Charts

on:
  workflow_run:
    workflows: ["Docker Image"]
    types:
      - completed

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Ensure `gh-pages` Exists
        run: |
          git fetch origin gh-pages || git checkout --orphan gh-pages
          git checkout gh-pages
          [ -f index.yaml ] || echo '{}' > index.yaml
          git add index.yaml
          git commit -m "Ensure gh-pages branch has index.yaml" || true
          git push origin gh-pages

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          charts_dir: helm
