name: Release Helm Charts

concurrency: release-helm

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'helm/**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Branch (Source)
        uses: actions/checkout@v3
        with:
          path: 'src'
          ref: 'main'
          fetch-depth: 0

      - name: Checkout GitHub Pages Branch (Destination)
        uses: actions/checkout@v3
        with:
          path: 'dest'
          ref: 'gh-pages'
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Package and Index Helm Chart
        shell: bash
        working-directory: src
        run: |
          # Define paths
          CHART_NAME="keepup"
          CHARTS_DIR="./helm/${CHART_NAME}"
          DEST_DIR="../dest/helm"

          # Ensure directories exist
          mkdir -p ${DEST_DIR}

          # Package Helm chart (excluding configs/)
          echo "Packaging Helm chart: ${CHART_NAME}"
          helm package "${CHARTS_DIR}" --destination "${DEST_DIR}"

          # Update Helm repo index
          echo "Updating Helm repo index..."
          helm repo index ${DEST_DIR} --merge ../dest/index.yaml --url "https://raw.githubusercontent.com/${{ github.repository }}/gh-pages/helm/"

      - name: Commit and Push Updates to Main Branch
        shell: bash
        working-directory: src
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add .
          git commit -m "Updated Helm charts from ref: $GITHUB_SHA" || echo "No changes to commit"
          git push

      - name: Commit and Push Updated Helm Repo to GitHub Pages
        shell: bash
        working-directory: dest
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add $(git ls-files -o --exclude-standard)
          git add index.yaml
          git commit -m "Updated Helm repo index from ref: $GITHUB_SHA" || echo "No changes to commit"
          git push
