name: Release Charts

on:
  workflow_run:
    workflows: ["Docker Image"]
    types:
      - completed

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Delete Previous Release (Force Update)
        continue-on-error: true
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          gh release delete $latest_tag --yes || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Force Push Updated Chart to gh-pages
        run: |
          git fetch origin gh-pages
          git checkout gh-pages
          git add .
          git commit -m "Force update Helm chart"
          git push origin gh-pages --force
