name: Release Charts

on:
  workflow_run:
    workflows: ["Docker Image"]
    types:
      - completed

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Update Chart Version (Force Release)
        run: |
          chart_path="charts/my-app/Chart.yaml"
          new_version=$(date +'%Y.%m.%d.%H%M%S')  # Generates a timestamp-based version
          echo "Setting chart version to $new_version"
          sed -i "s/^version: .*/version: $new_version/" "$chart_path"
          cat "$chart_path"  # Debugging output to check changes

      - name: Commit and Push Updated Chart Version
        run: |
          git add charts/my-app/Chart.yaml
          git commit -m "Force update Helm chart version to $new_version"
          git push origin main
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
